-- =============================================================================
-- schema.sql has been retired as the fresh-install source of truth.
-- =============================================================================
-- This file used to be a single hand-maintained snapshot of the whole schema,
-- meant to be pasted into the Supabase SQL Editor for a new project. It has
-- fallen out of sync with reality: migrations 0005 through 0015 were applied
-- directly to the live Supabase project (via the Supabase MCP connection and,
-- earlier, some other route) without ever being run against — or copied back
-- into — this local checkout. By the time this was caught, the live database
-- had a `vendors` table, a generic `lookup_options` reference-data system
-- driving every status/category/priority field, a `bidding_schedule_activities`
-- table, and a restructured `project_charter_funding`, none of which this
-- file knew about. Hand-transcribing all of that back into one 700+ line DDL
-- file from introspection risked shipping a subtly wrong "source of truth" —
-- worse than admitting the file needs regenerating with the right tool.
--
-- supabase/migrations/ (0001 through 0015) is now the actual source of
-- truth — every one of those files is either the exact SQL that was applied
-- historically (0005–0012, reconstructed from
-- supabase_migrations.schema_migrations on the live project) or a new
-- migration written and verified this session (0013–0015).
--
-- To bootstrap a new environment (local dev DB, a second Supabase project,
-- CI):
--   supabase db push          -- applies supabase/migrations/*.sql in order
-- To pull a fresh, byte-accurate schema.sql snapshot from the live project
-- once you want one again:
--   supabase db pull          -- or: supabase db dump --schema public -f supabase/schema.sql
--
-- See supabase/SCHEMA_RESTRUCTURE.md for the full account of what changed
-- and why.
-- =============================================================================
